### ISSUE TITLE
CI failing: updates for numpy 1.24 and scipy 1.10 needed

### ISSUE THREAD

**Issue by llimeht** [bumps/bumps#118]
As well as updating CI to drop the unsupported Python 3.6 that was causing CI to fail (see #117), bumps also needs code updates for numpy 1.24 and scipy 1.10

### scipy 1.10

There seem to be changes around covariance matrix - I've not spotted the relevant information in the release notes, however. Reported failure is:

```
=================================== FAILURES ===================================
_____________________________________ test _____________________________________

    def test():
        """check entropy estimates from known distributions"""
        # entropy test is optional: don't test if sklearn is not installed
        try:
            import sklearn
        except ImportError:
            return
    
        # Smoke test - do all the methods run in 1-D and 10-D?
        _check_smoke(stats.norm(10, 8))
        if hasattr(stats, 'multivariate_normal'):
            _check_smoke(stats.multivariate_normal(cov=np.diag([1]*10)))
    
        D = stats.norm(10, 8)
        _check_entropy("N[100,8]", D, N=2000)
        _check_entropy("N[100,8]", D, N=12000)
        if hasattr(stats, 'multivariate_normal'):
            D = stats.multivariate_normal(cov=np.diag([1, 12**2, 0.2**2]))
            _check_entropy("MVN[1,12,0.2]", D)
            D = stats.multivariate_normal(cov=np.diag([1]*10))
            _check_entropy("MVN[1]*10", D, N=10000)
            # Make sure zero-width dimensions return H = -inf
            D = MVNSingular(cov=np.diag([1, 1, 0]))
>           _check_entropy("MVN[1,1,0]", D, N=10000)

bumps/dream/entropy.py:1074: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
bumps/dream/entropy.py:1010: in _check_entropy
    H = D.entropy()/LN2
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <bumps.dream.entropy.MVNSingular object at 0x7fb56e207100>, N = 10000

    def entropy(self, N=10000):
        with np.errstate(divide='ignore'):
>           return 0.5*log(np.linalg.det((2*pi*np.e)*self.dist.cov))
E           AttributeError: 'multivariate_normal_frozen' object has no attribute 'cov'

bumps/dream/entropy.py:863: AttributeError
```
Forcing CI to downgrade to scipy 1.8 makes the error go away so this seems to be scipy related; that's obviously not a long term strategy for bumps.

### numpy 1.24
The most recent release of numpy has finally dropped support for the `np.float` function and dtype. Callers should be specific about the byte size requested and use `np.float64`. 

The `check_fitters` stage of CI currently fails with numpy 1.24:

```
====== fitter: lm
Traceback (most recent call last):
  File "/home/runner/work/bumps/bumps/run.py", line 65, in <module>
    bumps.cli.main()
  File "/home/runner/work/bumps/bumps/bumps/cli.py", line 704, in main
    best, fbest = fitdriver.fit(resume=resume_path)
  File "/home/runner/work/bumps/bumps/bumps/fitters.py", line 970, in fit
    x, fx = fitter.solve(monitors=self.monitors,
  File "/home/runner/work/bumps/bumps/bumps/fitters.py", line 567, in solve
    result = mpfit(
  File "/home/runner/work/bumps/bumps/bumps/mpfit.py", line 901, in __init__
    xall = numpy.asarray(xall, numpy.float)
  File "/opt/hostedtoolcache/Python/3.10.9/x64/lib/python3.10/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float'. Did you mean: 'cfloat'?
```
A quick grep of the code makes it look like `bumps/mpfit.py` is the only place using these deprecated functions; changing them all to `float64` looks safe.

It's curious that these failures were only picked up in the `check_fitters` stage and not in the pytest stage -- is that expected (or is that something that should be changed?)

**Comment by drew-parsons** [comment]
> The most recent release of numpy has finally dropped support for the np.float function and dtype. Callers should be specific about the byte size requested and use np.float64.

Just using the standard python type `float` is also an option, and should give the same behaviour (same precision) as before.  Using `np.float64` would give more consistency, however,  removing architecture-dependent variability.

**Comment by drew-parsons** [comment]
The multivariate_normal_frozen cov error is no doubt related to the introduction of the Covariance class,  https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.Covariance.html#scipy.stats.Covariance 

As far as I can tell, the in-line documentation for stats._multivariate.multivariate_normal_frozen does not match the class definition. There is no `r.cov` property.  I'm not entirely sure what bumps.dream is expecting here, but it might be that it now wants `self.dist.cov_object.covariance` here instead of `self.dist.cov`.

According to the bumps/dream/entropy.py documention, the MVNSingular class was added because scipy MVN gave the wrong entropy for singular (and near singular) matrices.  Given the large changes made to scipy.stats.multivariate_normal, it might be worth checking scipy's MVN to see if it now works as required, and drop bumps.dream.entropy.MVNSingular if it's no longer needed.

**Comment by bmaranville** [comment]
It looks like scipy stopped attaching the 'cov' attribute to multivariate distribution classes with this commit: https://github.com/scipy/scipy/commit/e13d4f35f405ec222e23f4b1e98fe32ddaf3f558

This attribute is being used in MVNSingular class, in the entropy() method, in bumps.dream.entropy (that class is used for singular covariance matrices).

They are now attaching 'cov_object', and you can get to the covariance with e.g. `dist.cov_object.covariance` instead of `dist.cov` but that is unfortunately a breaking change for versions of scipy < 1.10.

**Comment by drew-parsons** [comment]
A simple work around (to work with both old and new scipy) is to change it to
```
    def entropy(self, N=10000):
        # scipy 1.10 changed Covariance handling in stats, allow for that change 
        cov = getattr(self.dist, 'cov', self.dist.cov_object.covariance)
        with np.errstate(divide='ignore'):
            return 0.5*log(np.linalg.det((2*pi*np.e)*cov))

```

**Comment by drew-parsons** [comment]
Wait, no.  That formulation gives the reverse error with scipy 1.8, it's not used conditionally. Need to keep the two versions separate
```
if hasattr(self.dist, 'cov'):
    cov = self.dist.cov
else:
    cov = self.dist.cov_object.covariance
```
or use a `try...except AttributeError` structure
