### ISSUE TITLE
CorrelationView not updated if number of parameters > 15

### ISSUE THREAD

**Issue by krzywon** [bumps/bumps#134]
In bumps.gui.uncertainty_view CorrelationView, if a fit is run with 15 or fewer parameters, and then a subsequent fit is run using more parameters and the same persistent CorrelationView object, plots from the original fit remains. I understand, that when more than 15 parameters are fit, the correlation plots are not generated for various reasons, but not removing previous plots seems counter-intuitive.

**Comment by bmaranville** [comment]
In general I think this type of view is by default left open because it is "hard to calculate", and users might want to look at it even after they run other fits like LM or Amoeba.  But when a user runs another DREAM fit, I agree that it's confusing to leave the old plot there even after newer populations have been generated, but not shown (because of an arbitrary limit on num. parameters to show).
