### ISSUE TITLE
--pars not loading parameters correctly if model labels aren't unique

### ISSUE THREAD

**Issue by ohcpaull** [bumps/bumps#35]
Loading saved parameters in bumps doesn't work properly when the model labels are not unique. This can be the case when defining superlattices with multiple repetitions of the same material layers. In bumps.cli.load_best() a dict is created that reassigns parameters to the first instance of the model label if there are multiple identical labels.

**Comment by pkienzle** [comment]
Duplicate parameter names should now be supported.

The problem is somewhat ill-defined: in addition to reloading existing model parameters, this function is designed to allow existing parameters to be loaded into a modified model, even if the model has new, deleted or rearranged parameters. I'm keeping track of the order of the values for a given parameter name as I load them from the file, and I assign them to the model one after another as they appear. That means that if you add a new parameter of the same name before an existing parameter, it will get the existing parameter value, and the existing parameter will get the default value. Not ideal, but there is no good solution when duplicate parameter names are allowed.

**Comment by pkienzle** [comment]
... supported as of next release, which should be soon.
