### ISSUE TITLE
sphinx unused citation warnings 

### ISSUE THREAD

**Issue by llimeht** [bumps/bumps#38]
The copy of `optimzer.rst` within the SasView source code has received several updates to ensure that all the citations are used within the source. These changes have not been applied to the original document in bumps, meaning that it generates the following:

> …/doc/guide/optimizer.rst:127: WARNING: Citation [Levenberg1944] is not referenced.                                                            
> …/doc/guide/optimizer.rst:132: WARNING: Citation [Marquardt1963] is not referenced.                                                                                    
> …/doc/guide/optimizer.rst:208: WARNING: Citation [Nelder1965] is not referenced.                                                                                       
> …/doc/guide/optimizer.rst:272: WARNING: Citation [Dennis1987] is not referenced.                                                                                       
> …/doc/guide/optimizer.rst:352: WARNING: Citation [Storn1997] is not referenced.                                                                                        
> …/doc/guide/optimizer.rst:586: WARNING: Citation [Vrugt2009] is not referenced.                                                                                        
> …/doc/guide/optimizer.rst:593: WARNING: Citation [Kramer2010] is not referenced.                                                                                       
> …/doc/guide/optimizer.rst:599: WARNING: Citation [JCGM2008] is not referenced.                                                                                         
> …/doc/guide/optimizer.rst:646: WARNING: Citation [Kennedy1995] is not referenced.                                                                                      
> …/doc/guide/optimizer.rst:702: WARNING: Citation [Sahin2013] is not referenced.                                                                                        
> …/doc/guide/optimizer.rst:754: WARNING: Citation [Swendsen1986] is not referenced.                                                                                     

Two things need fixing

1. update the version of the document here in bumps
2. stop SasView embedding the document but instead collect it from bumps at build time (or properly separate the packages)

**Comment by pkienzle** [comment]
I resolved the unreferenced citation warnings by referencing all the citations.

Re: SasView docs, I don't see a good solution.

Given that SasView will require the source tree for sasmodels to build the docs (and eventually sascalc) it will be stuck with a complicated build.

I suppose we could simplify it slightly by copying the relevant bits of bumps documentation to the SasView doc tree. We would need to update it whenever with update the bumps version dependency, but we could automate this with the same code we currently have.

SasView should be doing something similar with periodictable, so that information such as the formula syntax and the calculation algorithms are available in the SasView manual.

A further complication: the SasView Qt gui no longer uses the bumps wx fit selection widget so the screen shots are wrong. A solution to this would be to move the qt gui selector into the bumps package and select the appropriate screen shots when generating the bumps docs.

**Comment by pkienzle** [comment]
Transferred to https://github.com/SasView/sasview/issues/1808
